server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/km?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  application:
    name: km-main-admin

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
